"""adding the forgeign key to the routes from company

Revision ID: 03f529fd0469
Revises: 88699ddeb3f9
Create Date: 2025-09-03 23:20:20.176172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03f529fd0469'
down_revision: Union[str, Sequence[str], None] = '88699ddeb3f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('company_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'tickets', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'company_id')
    # ### end Alembic commands ###
