"""make payments.user_id nullable and set ON DELETE SET NULL

Revision ID: 13205d264c33
Revises: 3ec0f41efa0c
Create Date: 2025-08-28 20:32:21.351950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13205d264c33'
down_revision: Union[str, Sequence[str], None] = '3ec0f41efa0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tickets', 'route_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tickets', 'mode',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'active'"))
    op.create_foreign_key(None, 'tickets', 'routes', ['route_id'], ['id'])
    op.alter_column('users', 'role',
               existing_type=sa.NullType(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.NullType(),
               nullable=True)
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.alter_column('tickets', 'mode',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'active'"))
    op.alter_column('tickets', 'route_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('payments', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
