"""hh

Revision ID: 79690f20031a
Revises: 
Create Date: 2025-09-07 11:20:27.817440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79690f20031a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bus_stations', 'company_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('bus_stations', 'created_at')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.add_column('routes', sa.Column('name', sa.String(), nullable=False))
    op.add_column('routes', sa.Column('origin_station_id', sa.String(), nullable=True))
    op.add_column('routes', sa.Column('destination_station_id', sa.String(), nullable=True))
    op.alter_column('routes', 'price',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.create_foreign_key(None, 'routes', 'bus_stations', ['destination_station_id'], ['id'])
    op.create_foreign_key(None, 'routes', 'bus_stations', ['origin_station_id'], ['id'])
    op.drop_column('routes', 'created_at')
    op.drop_column('routes', 'updated_at')
    op.drop_column('routes', 'origin')
    op.drop_column('routes', 'destination')
    op.add_column('schedules', sa.Column('bus_id', sa.String(), nullable=True))
    op.add_column('schedules', sa.Column('route_segment_id', sa.String(), nullable=True))
    op.alter_column('schedules', 'company_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'schedules', 'buses', ['bus_id'], ['id'])
    op.create_foreign_key(None, 'schedules', 'route_segments', ['route_segment_id'], ['id'])
    op.drop_column('schedules', 'route_station_id')
    op.drop_constraint(op.f('tickets_route_id_fkey'), 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'route_id')
    op.drop_column('tickets', 'mode')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.add_column('tickets', sa.Column('mode', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tickets', sa.Column('route_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('tickets_route_id_fkey'), 'tickets', 'routes', ['route_id'], ['id'])
    op.add_column('schedules', sa.Column('route_station_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.alter_column('schedules', 'company_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('schedules', 'route_segment_id')
    op.drop_column('schedules', 'bus_id')
    op.add_column('routes', sa.Column('destination', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('routes', sa.Column('origin', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('routes', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('routes', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'routes', type_='foreignkey')
    op.drop_constraint(None, 'routes', type_='foreignkey')
    op.alter_column('routes', 'price',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('routes', 'destination_station_id')
    op.drop_column('routes', 'origin_station_id')
    op.drop_column('routes', 'name')
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.add_column('bus_stations', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('bus_stations', 'company_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
