"""adding the forgeign key to the routes from company

Revision ID: 88699ddeb3f9
Revises: fb6909f66547
Create Date: 2025-09-03 23:15:21.382286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88699ddeb3f9'
down_revision: Union[str, Sequence[str], None] = 'fb6909f66547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('company_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'routes', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'routes', type_='foreignkey')
    op.drop_column('routes', 'company_id')
    # ### end Alembic commands ###
