"""initial_schema_creation

Revision ID: 984714a13bc8
Revises: 
Create Date: 2025-11-25 11:28:09.427344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '984714a13bc8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('routes_company_id_fkey'), 'routes', type_='foreignkey')
    op.drop_column('routes', 'company_id')
    op.drop_column('routes', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('routes', sa.Column('company_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('routes_company_id_fkey'), 'routes', 'companies', ['company_id'], ['id'])
    op.drop_column('routes', 'updated_at')
    # ### end Alembic commands ###
