"""Adding buses to buse_schedule as a many-to-many relation ship to schedules

Revision ID: b640e6bec48e
Revises: 2ab159689540
Create Date: 2025-09-05 10:02:21.219542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b640e6bec48e'
down_revision: Union[str, Sequence[str], None] = '2ab159689540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
