"""Next migration

Revision ID: d2f61ab1c0db
Revises: e8dd8672d287
Create Date: 2025-08-29 18:42:15.610821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2f61ab1c0db'
down_revision: Union[str, Sequence[str], None] = 'e8dd8672d287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tickets', 'route_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tickets', 'mode',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'active'"))
    op.create_foreign_key(None, 'tickets', 'routes', ['route_id'], ['id'])
    op.add_column('users', sa.Column('username', sa.String(), nullable=False))
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=False))
    op.alter_column('users', 'id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'password')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.NullType(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('password', sa.VARCHAR(), nullable=False))
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.VARCHAR(), nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'username')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.alter_column('tickets', 'mode',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'active'"))
    op.alter_column('tickets', 'route_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('payments', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
