"""adding the forgeign key to the bus from company

Revision ID: fb6909f66547
Revises: aed0498dc208
Create Date: 2025-09-03 23:14:20.601501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb6909f66547'
down_revision: Union[str, Sequence[str], None] = 'aed0498dc208'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buses', sa.Column('company_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'buses', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'buses', type_='foreignkey')
    op.drop_column('buses', 'company_id')
    # ### end Alembic commands ###
